# Generated by Django 5.2.8 on 2025-11-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
